name: Linting

on:
  push:
  pull_request:
  # branches:
  #   - main
  #   - prod
  #   - ENV-prod
  #   - "*"

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hadolint/hadolint-action@v3.1.0
        name: Flask lint
        with:
          dockerfile: flask/Dockerfile
      - uses: hadolint/hadolint-action@v3.1.0
        name: Streamlit lint
        with:
          dockerfile: streamlit/Dockerfile
